######################################################################
# Automatically generated by qmake (3.0) Wed Apr 17 10:35:56 2019
######################################################################

TEMPLATE = app
TARGET = qt_exampl
INCLUDEPATH += .

# Input
HEADERS += window.hpp
SOURCES += main.cpp window.cpp
